add_newline = false
command_timeout = 1000

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'

[battery]
disabled = true

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
symbol = " "
format = "[$symbol($version)]($style) "

[python]
symbol = " "
format = "[$symbol($version)]($style) "

[rust]
symbol = " "
format = "[$symbol($version)]($style) "

[golang]
symbol = " "
format = "[$symbol($version)]($style) "

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '[$symbol$context( \($namespace\))]($style) '
style = "bold purple"
# 特定のコンテキストのみ表示する場合はdetect_filesやcontextsで制御可能
# [kubernetes.context_aliases]
# "arn:aws:eks:.*:.*:cluster/(?P<var_cluster>[\\w-]+)" = "$var_cluster"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

